const fs = require("fs");
const path = require("path");
const PDFDocument = require("pdfkit");
const { getExportMeta, htmlToPlainText } = require("./exportArticleTemplate");
const APP_NAME = process.env.APP_NAME || "Real Write";

const COLORS = {
  primary: "#0d2b22",
  primary2: "#476459",
  surface: "#f6f3f2",
  border: "#e5e2e1",
  text: "#1c1b1b",
  muted: "#727975"
};

function drawMetaGrid(doc, meta) {
  const left = doc.page.margins.left;
  const width = doc.page.width - doc.page.margins.left - doc.page.margins.right;
  const colWidth = width / 2;
  const rowHeight = 34;
  const startY = doc.y;

  meta.forEach(([label, value], index) => {
    const col = index % 2;
    const row = Math.floor(index / 2);
    const x = left + col * colWidth;
    const y = startY + row * rowHeight;
    doc.roundedRect(x, y, colWidth - 8, rowHeight - 6, 6).fillAndStroke(COLORS.surface, COLORS.border);
    doc.fillColor(COLORS.muted).font("Helvetica-Bold").fontSize(7).text(label.toUpperCase(), x + 9, y + 7, { width: colWidth - 26 });
    doc.fillColor(COLORS.text).font("Helvetica").fontSize(9).text(String(value || "-"), x + 9, y + 18, { width: colWidth - 26 });
  });

  doc.y = startY + Math.ceil(meta.length / 2) * rowHeight + 10;
}

function sectionTitle(doc, title) {
  doc.moveDown(0.8);
  doc.fillColor(COLORS.primary).font("Helvetica-Bold").fontSize(11).text(title.toUpperCase());
  doc.moveTo(doc.page.margins.left, doc.y + 3).lineTo(doc.page.width - doc.page.margins.right, doc.y + 3).strokeColor(COLORS.border).stroke();
  doc.moveDown(0.6);
}

function exportArticlePdf({ article, writerName, projectTitle, downloadedAt = new Date() }) {
  const doc = new PDFDocument({ margin: 46, size: "A4", info: { Title: article.title || `${APP_NAME} article` } });
  const logoPath = path.join(__dirname, "..", "public", "assets", "realwrite-logo.png");
  const contentWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;

  doc.roundedRect(46, 36, contentWidth, 82, 12).fill(COLORS.primary);
  if (fs.existsSync(logoPath)) doc.image(logoPath, 62, 52, { width: 42, height: 42 });
  doc.fillColor("#ffffff").font("Helvetica-Bold").fontSize(10).text(String(APP_NAME || "").toUpperCase(), 116, 54, { characterSpacing: 0.8 });
  doc.font("Helvetica-Bold").fontSize(22).text(article.title || "Untitled", 116, 70, { width: contentWidth - 88, lineGap: 2 });
  doc.fillColor("#dce7e2").font("Helvetica").fontSize(9).text("Article export", 116, 98);
  doc.y = 136;

  drawMetaGrid(doc, getExportMeta({ article, writerName, projectTitle, downloadedAt }));

  if (article.short_description) {
    sectionTitle(doc, "Short description");
    doc.fillColor(COLORS.text).font("Helvetica-Oblique").fontSize(11).text(article.short_description, { lineGap: 4 });
  }

  sectionTitle(doc, "Long description");
  const body = htmlToPlainText(article.long_description || "");
  doc.fillColor(COLORS.text).font("Helvetica").fontSize(11).text(body || "-", { lineGap: 4 });

  if (article.manager_note) {
    sectionTitle(doc, "Manager remark");
    doc.fillColor(COLORS.text).font("Helvetica").fontSize(10).text(article.manager_note, { lineGap: 3 });
  }

  doc
    .fontSize(8)
    .fillColor(COLORS.muted)
    .text(`Generated by ${APP_NAME}`, doc.page.margins.left, doc.page.height - 34, { align: "center", width: contentWidth });

  return doc;
}

module.exports = { exportArticlePdf };
